#配置pytest默认运行参数
#在实际工作中几千个测试用例，多人协作，如果每个人的参数乱写，会导致项目混乱，所以才有pytest.ini文件，团队统一规则

#[pytest]
#addopts = -s -v
#在命令行输入pytest，相当于 pytest -s -v

#testpaths = testcases
#pytest 默认去 testcases 目录找用例

#python_files = test_*.py
#配置用例命名规则

; python_functions = test_*
; 配置函数名规则

; python_classes = Test*
; 配置类名规则

; pythonpath = .
; 配置 Python 路径，把项目根目录加入 sys.path，这样在测试用例中就可以直接导入项目中的模块了。

[pytest]
pythonpath = .
addopts = -s -v
testpaths = testcases
python_files = test_*.py